# Generated by Django 2.1.4 on 2019-01-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='contact',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
